// Expansion module registration and configurator contracts.
export type {
  CardAlternateBuyOption,
  CardAlternateBuyOptionApplyContext,
  CardAlternateBuyOptionApplyResult,
  CardAlternateBuyOptionCanBuyContext,
  CardExpansionActionConditionMap,
  CardExpansionModule,
  ClientEventRegistrar,
  EndGameConditionRegistrar,
  EndGamePolicyFn,
  EndGamePolicyFnOutcome,
  EndGamePolicyRegistrar,
  ExpansionConfigurator,
  ExpansionConfiguratorContext,
  ExpansionConfiguratorFactory,
  GameEventRegistrar,
  InitializeExpansionContext,
  PlayerScoreDecorator,
  PlayerScoreDecoratorRegistrar,
} from '../types.ts';
