FROM denoland/deno:2.7.7

WORKDIR /app

COPY shared/ ./shared/
COPY server/ ./server/

WORKDIR /app/server

RUN deno install --entrypoint src/server.ts && \
    find src -name '*.ts' -print0 | xargs -0 deno cache && \
    chown -R deno:deno /deno-dir && \
    mkdir -p /app/server/game-data && \
    chown -R deno:deno /app/server/game-data

ENV PORT=3000

USER deno

EXPOSE $PORT

CMD ["deno", "run", \
  "--allow-net", \
  "--allow-env", \
  "--allow-read", \
  "--allow-write", \
  "--allow-sys", \
  "--unstable-kv", \
  "--node-modules-dir=manual", \
  "src/server.ts"]
