-- Storage schema for all server-side persistence.
--
-- All tables are accessed exclusively through the Supabase service-role key
-- from the server process. Row Level Security (RLS) is intentionally not
-- enabled — the service-role key bypasses RLS anyway, and the server is the
-- sole writer/reader.
--
-- BIGINT is used for all timestamp columns to match JS Date.now()-style
-- millisecond integers without parsing overhead.
--
-- INTEGER is used for auth_users.id so it round-trips cleanly as a JS number.

-- Users registered with the password auth provider.
CREATE TABLE auth_users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL,
  username_lower TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  password_algo TEXT NOT NULL CHECK (password_algo IN ('argon2id', 'bcrypt')),
  password_updated_at BIGINT NOT NULL,
  failed_attempts INTEGER NOT NULL DEFAULT 0,
  locked_until BIGINT,
  disabled BOOLEAN NOT NULL DEFAULT false,
  is_admin BOOLEAN NOT NULL DEFAULT false,
  created_at BIGINT NOT NULL,
  -- NULL for password users; reserved for future OAuth / Supabase Auth hook.
  supabase_auth_id UUID UNIQUE
);

-- Active auth sessions. Indexed by username and expiry for efficient cleanup.
CREATE TABLE auth_sessions (
  token TEXT PRIMARY KEY,
  username TEXT NOT NULL,
  provider_name TEXT NOT NULL,
  created_at BIGINT NOT NULL,
  last_activity_at BIGINT NOT NULL,
  expires_at BIGINT NOT NULL,
  created_from_ip TEXT,
  created_from_user_agent TEXT
);

CREATE INDEX idx_auth_sessions_username ON auth_sessions (username);
CREATE INDEX idx_auth_sessions_expires_at ON auth_sessions (expires_at);

-- Invite-style registration codes. Not filtered by expiry at load time so
-- the admin list endpoint can show all codes including expired ones.
CREATE TABLE auth_registration_codes (
  code TEXT PRIMARY KEY,
  created_at BIGINT NOT NULL,
  created_by TEXT NOT NULL,
  expires_at BIGINT,
  max_uses INTEGER NOT NULL,
  used_count INTEGER NOT NULL DEFAULT 0,
  disabled BOOLEAN NOT NULL DEFAULT false
);

-- Named match-configuration saves. Composite PK ensures each user has at
-- most one save per normalized save_key.
CREATE TABLE match_configuration_saves (
  username_lower TEXT NOT NULL,
  save_key TEXT NOT NULL,
  display_name TEXT NOT NULL,
  data JSONB NOT NULL,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  PRIMARY KEY (username_lower, save_key)
);

CREATE INDEX idx_match_configuration_saves_username ON match_configuration_saves (username_lower);

-- Grants for the storage tables. Tables created via raw SQL migrations do not
-- automatically receive the per-role default privileges that the Supabase
-- table editor would apply, which causes service_role API calls to fail with
-- `permission denied for table` (SQLSTATE 42501). Granting ALL to service_role
-- restores the expected behavior; anon/authenticated are intentionally not
-- granted because all access is mediated by the server using the secret key.
GRANT USAGE ON SCHEMA public TO service_role;
GRANT ALL ON auth_users, auth_sessions, auth_registration_codes, match_configuration_saves TO service_role;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO service_role;
